# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.TextField()),
                ('buyer_location', models.TextField()),
                ('product', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_image', models.ImageField(null=True, upload_to='image/')),
                ('product', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
