# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='image/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=10)),
            ],
        ),
    ]
